# Generated by Django 5.1.1 on 2024-09-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date_created',
            new_name='date_posted',
        ),
    ]
